server:
  port: 8888

spring:
  application:
    name: blog-config
  cloud:
    config:

      server:
        #        native:
        #          search-locations: classpath:configs
        encrypt:
          enabled: false

        git:
          uri: https://github.com/Darkb0ne/SKS-Blog-WS2021-Cloud-Config-Repo
          search-paths: '{application}'
          clone-on-start: true
          default-label: master
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    refresh:
      enabled: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://netflix:eureka@localhost:8761/eureka/

encrypt:
  key: topsecret
